### ISSUE TITLE
background-image has quotes escaped

### ISSUE THREAD

**Issue by obartra** [1N50MN14/html-element#19]
Since all properties are escaped, setting a url on `background-image` sets the wrong value on `outerHTML`.

E.g.: `url("somewhere.jpg")` becomes `url(&quot;somewhere.jpg&quot;)`

My guess is that we don't want to escape double quotes at all and just rely on user input.

**Comment by obartra** [comment]
Actually, after some more thought, since this is whithin a style tag `url("...` would be invalid anyway

**Comment by 1N50MN14** [comment]
Yup :-)

**Comment by obartra** [comment]
I was running into this issue when using virtual-dom in the browser but it was not an html-element issue.

Basically when creating an element (at least on Chrome) single quotes are replaced with double quotes. These in turn, when calling outerHTML, they are (correctly) replaced with `&quot;` by html-element.

```javascript
var div = document.createElement('div');
div.style.backgroundImage = "url('test.jpg')";
div.style.backgroundImage; //"url(\"test.jpg\")"
```

I worked around that by just replacing output `&quot;` with `'`, something like:

```javascript
outerHTML.replace(/&quot;/g, '\'');
```

Posting it here in case it's useful for anybody else but it looks out of the scope of html-element.
