### ISSUE TITLE
npm version bump

### ISSUE THREAD

**Issue by jimdebeer** [1N50MN14/html-element#27]
hey @1N50MN14 could you perhaps publish a minor npm version? would be super helpful!

**Comment by 1N50MN14** [comment]
Yes ofcourse! Is it ok for you if I do that tomorrow when I'm infront of my PC?

**Comment by jimdebeer** [comment]
of course man! thx a million

**Comment by 1N50MN14** [comment]
bumped and npm published thanks again for the awesome PR!
