### ISSUE TITLE
support for createShadowRoot method

### ISSUE THREAD

**Issue by tusharmath** [1N50MN14/html-element#35]
This could be something really awesome because that would let people like me render web-components on the server side.

**Comment by tdumitrescu** [comment]
FYI I'm doing some server-side web component rendering (main reason I started looking at this repo). I'm taking the approach however of 'polyfilling' in my own code, much like the browser polyfills (e.g. adding component lifecycle hooks into the Element class). IMO the official API is kind of still too unstable to bake it into a DOM repo like this one directly for right now. For instance, the method that you mention, `createShadowRoot`, is officially deprecated, and set to be replaced by `attachShadow`, which is currently not implemented natively _anywhere_ (https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow).

Feel free to get in touch (email in GitHub profile) if you want to discuss approaches or collaborate.

**Comment by 1N50MN14** [comment]
Have to agree with @tdumitrescu on this one we should keep it basic and fully compatible imho

**Comment by tusharmath** [comment]
thanks for the feedback.
