### ISSUE TITLE
Find a way to not export globals

### ISSUE THREAD

**Issue by Raynos** [1N50MN14/html-element#8]
If your module didn't pollute global space it would be a nicer citizen.

Maybe have `html-element` either export `window.document` or `new Document()` based on environment. Then patch hyper-script to `var document = require('html-element')`

**Comment by jimdebeer** [comment]
This is obviously a really good idea @1N50MN14 what do you think? As an alternative could also expose a module that has all globals, would this be something you would accept in a pull req?

```javascript
var window = require('html-element/window')
// has window.document, window.Element etc
```

**Comment by 1N50MN14** [comment]
@jimdebeer The reason why I had to pollute global space is because initially it was used with other engines that expected the methods to be available; it's been quite some time now so I guess it makes sense to make the change - however, I'm concerned it's a breaking change specially since for some odd reason the module was installed from npm over 2K times last month only...

**Comment by jimdebeer** [comment]
yeah we could just add an entry in the repo that exposes a non-global way (so we don't change the api at all)

**Comment by 1N50MN14** [comment]
Yup sounds like a good idea

**Comment by tusharmath** [comment]
This has become a major issue while using jss as described here — https://github.com/cssinjs/jss/issues/292

I would make a lot more sense for `html-element` to not pollute the global ns.

**Comment by 1N50MN14** [comment]
@jimdebeer @tdumitrescu would you guys be interested in begin added as collaborators on the repo? it'll help speed up things at least until I get my head above water at work; the main thing for me is that we stick to tests like you've been doing so far and and PR's doesn't break compatibility with hyperscript. @tusharmath Looks like we'll need to get it to it now (though cssinjs could use a more elegant way of detecting node/browser)

**Comment by tdumitrescu** [comment]
Sure, I'd be happy to help out.

**Comment by 1N50MN14** [comment]
@tusharmath awesome! very much appreciated!

**Comment by jimdebeer** [comment]
sure man i can help some plp working at my company are doing some pull reqs etc so that will speed things up

**Comment by tusharmath** [comment]
@1N50MN14 Thanks for taking this into consideration. I would like to know how would you go about implementing this though? Since hyperscript too depends on the usage of the globally defined `document` object?

**Comment by 1N50MN14** [comment]
@jimdebeer awesome thank you! @tusharmath I'm not sure yet but as me and @jimdebeer discussed earlier we could make it so that you could do something like `var window = require('html-element/window')` would give you a scoped window, otherwise the existing behaviour remains intact.

**Comment by tusharmath** [comment]
This would require a fix to be made in the hyperscript lib as well isn't it? If you'd not mind I could too make the pull request.

**Comment by 1N50MN14** [comment]
I don't mind, `hyperscript` simply requires `html-element` once globally, in theory all it takes is to make separate local requires; see with dominic if he's fine with that

**Comment by tusharmath** [comment]
@1N50MN14 Could your take a look at #36
